# .readthedocs.yaml
# Read the Docs configuration file
# This file is for configuring readthedocs for MEWarpX

# Required
version: 2

# Build documentation in the docs/ directory with Sphinx
sphinx:
   configuration: mewarpx/docs/conf.py

build:
  image: latest
  apt_packages:
    - clang
    - cmake

# Optionally set the version of Python and requirements required to build your docs
python:
   version: 3.8
   install:
  #  - requirements: mewarpx/requirements.txt
   - method: pip
     path: mewarpx
     extra_requirements:
      - docs
